### ISSUE TITLE
gulp error

### ISSUE THREAD

**Issue by robozb** [StartBootstrap/startbootstrap-resume#303]
Hi There, 

The Gulp throws this error after successful "npm install".

Best Regards: Beci

npm --version
6.14.11

gulp --version
CLI version: 2.3.0
Local version: 3.9.1

```
gulp
ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (I:\Kivitelezes\PeterBurgerEU\Tarhely\gulpteszt\resume-bootstrap4-master\node_modules\natives\index.js:143:24)
    at Object.req [as require] (I:\Kivitelezes\PeterBurgerEU\Tarhely\gulpteszt\resume-bootstrap4-master\node_modules\natives\index.js:55:10)     
    at Object.<anonymous> (I:\Kivitelezes\PeterBurgerEU\Tarhely\gulpteszt\resume-bootstrap4-master\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

**Comment by robozb** [comment]
Further error:

```
gulp
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (108)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (I:\Kivitelezes\PeterBurgerEU\Tarhely\gulpteszt\resume-bootstrap4-master\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (I:\Kivitelezes\PeterBurgerEU\Tarhely\gulpteszt\resume-bootstrap4-master\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (I:\Kivitelezes\PeterBurgerEU\Tarhely\gulpteszt\resume-bootstrap4-master\node_modules\gulp-sass\index.js:166:21)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
```

**Comment by robozb** [comment]
> @robozb I've just tested it with Node version 10 (10.24.1), and `npm install` runs smoothly, and `gulp dev` as well. Live reload also works as expected.

I can confirm Stromi's comment, the gulp in this system didn't work up from the node.js 10.

What worked are these: 
![image](https://user-images.githubusercontent.com/8656998/201363324-ffb34061-5125-46b5-a81c-5cb2317b7b4b.png)
